import {createElement} from 'react';
import TestRenderer, {act} from 'react-test-renderer';
import {emptyAppData, type AppData} from '../types/domain';
import {adjustTaskReminderForQuietHours} from '../shared/notificationSettings';
import {createTaskRecord} from '../shared/taskLifecycle';
import {localDateKey} from '../shared/period';
import {taskReminders} from '../platform/taskReminders';
import {AppStoreProvider, useAppStore} from './AppStore';

jest.mock('../shared/attachmentFiles', () => ({
  deleteAttachmentFiles: jest.fn().mockResolvedValue(undefined),
}));

jest.mock('./nativeWorkspaceStore', () => ({
  createNativeWorkspaceStore: jest.fn(() => ({load: jest.fn(), save: jest.fn()})),
}));

jest.mock('../platform/taskReminders', () => ({
  taskReminders: {
    sync: jest.fn().mockResolvedValue(undefined),
    requestPermission: jest.fn().mockResolvedValue(undefined),
    schedule: jest.fn().mockResolvedValue(undefined),
    cancel: jest.fn().mockResolvedValue(undefined),
  },
}));

describe('AppStore task reminders', () => {
  it('can set a reminder immediately after creating the task', async () => {
    let saved = emptyAppData();
    const store = {
      load: async () => saved,
      save: async (next: AppData) => {
        saved = next;
      },
    };
    let value: ReturnType<typeof useAppStore> | null = null;
    const Probe = () => {
      value = useAppStore();
      return null;
    };
    let renderer: TestRenderer.ReactTestRenderer | undefined;

    await act(async () => {
      renderer = TestRenderer.create(createElement(AppStoreProvider, {store}, createElement(Probe)));
      await Promise.resolve();
      await Promise.resolve();
    });

    const triggerAtMillis = Date.now() + 60_000;
    let taskId = '';
    await act(async () => {
      taskId = await value!.addTask({title: 'New task', details: '', dueLocalDate: null, priority: 'normal', listId: 'task_list_inbox'});
      await value!.setTaskReminder(taskId, triggerAtMillis);
    });

    expect(saved.tasks.find(task => task.id === taskId)?.reminderAtMillis).toBe(triggerAtMillis);
    await act(async () => {
      renderer?.unmount();
    });
  });

  it('synchronizes a reminder generated by a recurring task rule', async () => {
    const now = new Date();
    now.setHours(8, 0, 0, 0);
    const nowSpy = jest.spyOn(Date, 'now').mockReturnValue(now.getTime());
    try {
      let saved = emptyAppData();
      const store = {
      load: async () => saved,
      save: async (next: AppData) => {
        saved = next;
      },
      };
      let value: ReturnType<typeof useAppStore> | null = null;
      const Probe = () => {
      value = useAppStore();
      return null;
      };
      let renderer: TestRenderer.ReactTestRenderer | undefined;

      await act(async () => {
        renderer = TestRenderer.create(createElement(AppStoreProvider, {store}, createElement(Probe)));
        await Promise.resolve();
        await Promise.resolve();
      });

      const sync = taskReminders.sync as jest.Mock;
      sync.mockClear();
      await act(async () => {
        await value!.addTaskRecurrence({
        title: 'Review tomorrow',
        details: '',
        priority: 'normal',
        listId: 'task_list_inbox',
        cadence: 'day',
        interval: 1,
        nextOccurrenceLocalDate: localDateKey(new Date()),
        missedOccurrencePolicy: 'all',
        reminderLocalTime: '23:59',
        });
      });

      const generatedTask = saved.tasks[0];
      expect(generatedTask?.reminderAtMillis).toBe(new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 0, 0).getTime());
      expect(sync).toHaveBeenLastCalledWith([{taskId: generatedTask?.id, triggerAtMillis: generatedTask?.reminderAtMillis}]);
      await act(async () => {
        renderer?.unmount();
      });
    } finally {
      nowSpy.mockRestore();
    }
  });

  it('restores a prior reminder using the quiet-hours projection when saving fails', async () => {
    const previousReminderAt = new Date();
    previousReminderAt.setDate(previousReminderAt.getDate() + 1);
    previousReminderAt.setHours(23, 0, 0, 0);
    const nextReminderAt = new Date(previousReminderAt);
    nextReminderAt.setMinutes(30);
    const existingTask = createTaskRecord(
      {title: 'Existing task', details: '', dueLocalDate: null, priority: 'normal', listId: 'task_list_inbox'},
      'task_existing',
      new Date().toISOString(),
    );
    existingTask.reminderAtMillis = previousReminderAt.getTime();
    let saved = {
      ...emptyAppData(),
      notificationSettings: {
        quietHoursStartLocalTime: '22:00',
        quietHoursEndLocalTime: '07:00',
        snoozeDurationMinutes: 30,
        taskRemindersEnabled: true,
      },
      tasks: [existingTask],
    } as AppData;
    const store = {
      load: async () => saved,
      save: async (next: AppData) => {
        if (next.tasks[0]?.reminderAtMillis === nextReminderAt.getTime()) {
          throw new Error('save failed');
        }
        saved = next;
      },
    };
    let value: ReturnType<typeof useAppStore> | null = null;
    const Probe = () => {
      value = useAppStore();
      return null;
    };
    let renderer: TestRenderer.ReactTestRenderer | undefined;

    await act(async () => {
      renderer = TestRenderer.create(createElement(AppStoreProvider, {store}, createElement(Probe)));
      await Promise.resolve();
      await Promise.resolve();
    });

    const schedule = taskReminders.schedule as jest.Mock;
    schedule.mockClear();
    await act(async () => {
      await expect(value!.setTaskReminder('task_existing', nextReminderAt.getTime())).rejects.toThrow('save failed');
    });

    expect(schedule).toHaveBeenNthCalledWith(1, 'task_existing', adjustTaskReminderForQuietHours(nextReminderAt.getTime(), saved.notificationSettings));
    expect(schedule).toHaveBeenNthCalledWith(2, 'task_existing', adjustTaskReminderForQuietHours(previousReminderAt.getTime(), saved.notificationSettings));
    await act(async () => {
      renderer?.unmount();
    });
  });

  it('does not revive a past reminder when quiet hours project future alarms', async () => {
    const now = new Date();
    const startHour = now.getHours();
    const endHour = (startHour + 1) % 24;
    const formatHour = (hour: number) => `${String(hour).padStart(2, '0')}:00`;
    const existingTask = createTaskRecord(
      {title: 'Past task', details: '', dueLocalDate: null, priority: 'normal', listId: 'task_list_inbox'},
      'task_past',
      new Date().toISOString(),
    );
    existingTask.reminderAtMillis = Date.now() - 60_000;
    const saved = {
      ...emptyAppData(),
      notificationSettings: {
        quietHoursStartLocalTime: formatHour(startHour),
        quietHoursEndLocalTime: formatHour(endHour),
        snoozeDurationMinutes: 60,
        taskRemindersEnabled: true,
      },
      tasks: [existingTask],
    } as AppData;
    const store = {
      load: async () => saved,
      save: jest.fn().mockResolvedValue(undefined),
    };
    const sync = taskReminders.sync as jest.Mock;
    sync.mockClear();
    let renderer: TestRenderer.ReactTestRenderer | undefined;

    await act(async () => {
      renderer = TestRenderer.create(createElement(AppStoreProvider, {store}, createElement(() => null)));
      await Promise.resolve();
      await Promise.resolve();
    });

    expect(sync).toHaveBeenCalledWith([]);
    await act(async () => {
      renderer?.unmount();
    });
  });

  it('completes a task from a reminder action once and keeps the logical reminder', async () => {
    const task = createTaskRecord(
      {title: 'Complete from reminder', details: '', dueLocalDate: null, priority: 'normal', listId: 'task_list_inbox'},
      'task_action',
      new Date().toISOString(),
    );
    task.reminderAtMillis = Date.now() + 60_000;
    let saved = {...emptyAppData(), tasks: [task]} as AppData;
    const store = {
      load: async () => saved,
      save: async (next: AppData) => {
        saved = next;
      },
    };
    let value: ReturnType<typeof useAppStore> | null = null;
    const Probe = () => {
      value = useAppStore();
      return null;
    };
    let renderer: TestRenderer.ReactTestRenderer | undefined;

    await act(async () => {
      renderer = TestRenderer.create(createElement(AppStoreProvider, {store}, createElement(Probe)));
      await Promise.resolve();
      await Promise.resolve();
    });

    const cancel = taskReminders.cancel as jest.Mock;
    cancel.mockClear();
    await act(async () => {
      await value!.completeTaskFromReminder('task_action');
      await value!.completeTaskFromReminder('task_action');
    });

    expect(saved.tasks[0]?.status).toBe('completed');
    expect(saved.tasks[0]?.reminderAtMillis).toBe(task.reminderAtMillis);
    expect(cancel).toHaveBeenCalledTimes(1);
    await act(async () => {
      renderer?.unmount();
    });
  });

  it('snoozes an open reminder for one hour using the quiet-hours projection', async () => {
    const nowMillis = 1_700_000_000_000;
    const nowSpy = jest.spyOn(Date, 'now').mockReturnValue(nowMillis);
    const task = createTaskRecord(
      {title: 'Snooze from reminder', details: '', dueLocalDate: null, priority: 'normal', listId: 'task_list_inbox'},
      'task_snooze',
      new Date(nowMillis).toISOString(),
    );
    task.reminderAtMillis = nowMillis - 60_000;
    let saved = {
      ...emptyAppData(),
      notificationSettings: {
        quietHoursStartLocalTime: '22:00',
        quietHoursEndLocalTime: '07:00',
        snoozeDurationMinutes: 30,
        taskRemindersEnabled: true,
      },
      tasks: [task],
    } as AppData;
    const store = {
      load: async () => saved,
      save: async (next: AppData) => {
        saved = next;
      },
    };
    let value: ReturnType<typeof useAppStore> | null = null;
    const Probe = () => {
      value = useAppStore();
      return null;
    };
    let renderer: TestRenderer.ReactTestRenderer | undefined;

    try {
      await act(async () => {
        renderer = TestRenderer.create(createElement(AppStoreProvider, {store}, createElement(Probe)));
        await Promise.resolve();
        await Promise.resolve();
      });

      const schedule = taskReminders.schedule as jest.Mock;
      const cancel = taskReminders.cancel as jest.Mock;
      schedule.mockClear();
      cancel.mockClear();
      await act(async () => {
        await value!.snoozeTaskFromReminder('task_snooze');
      });

      const snoozedAtMillis = nowMillis + 30 * 60 * 1000;
      expect(saved.tasks[0]?.reminderAtMillis).toBe(snoozedAtMillis);
      expect(cancel).toHaveBeenCalledWith('task_snooze');
      expect(schedule).toHaveBeenCalledWith('task_snooze', adjustTaskReminderForQuietHours(snoozedAtMillis, saved.notificationSettings));
    } finally {
      nowSpy.mockRestore();
      await act(async () => {
        renderer?.unmount();
      });
    }
  });

  it('ignores snooze actions for missing and completed tasks', async () => {
    const completedTask = createTaskRecord(
      {title: 'Already done', details: '', dueLocalDate: null, priority: 'normal', listId: 'task_list_inbox'},
      'task_completed_snooze',
      new Date().toISOString(),
    );
    completedTask.status = 'completed';
    completedTask.reminderAtMillis = Date.now() - 60_000;
    let saved = {...emptyAppData(), tasks: [completedTask]} as AppData;
    const store = {
      load: async () => saved,
      save: async (next: AppData) => {
        saved = next;
      },
    };
    let value: ReturnType<typeof useAppStore> | null = null;
    const Probe = () => {
      value = useAppStore();
      return null;
    };
    let renderer: TestRenderer.ReactTestRenderer | undefined;

    await act(async () => {
      renderer = TestRenderer.create(createElement(AppStoreProvider, {store}, createElement(Probe)));
      await Promise.resolve();
      await Promise.resolve();
    });

    const schedule = taskReminders.schedule as jest.Mock;
    const cancel = taskReminders.cancel as jest.Mock;
    schedule.mockClear();
    cancel.mockClear();
    await act(async () => {
      await value!.snoozeTaskFromReminder('missing_task');
      await value!.snoozeTaskFromReminder('task_completed_snooze');
    });

    expect(saved.tasks[0]?.status).toBe('completed');
    expect(saved.tasks[0]?.reminderAtMillis).toBe(completedTask.reminderAtMillis);
    expect(schedule).not.toHaveBeenCalled();
    expect(cancel).not.toHaveBeenCalled();
    await act(async () => {
      renderer?.unmount();
    });
  });

  it('pauses native task reminders without deleting logical reminder times', async () => {
    const task = createTaskRecord(
      {title: 'Pause reminder category', details: '', dueLocalDate: null, priority: 'normal', listId: 'task_list_inbox'},
      'task_pause_category',
      new Date().toISOString(),
    );
    task.reminderAtMillis = Date.now() + 60_000;
    let saved = {...emptyAppData(), tasks: [task]} as AppData;
    const store = {
      load: async () => saved,
      save: jest.fn(async (next: AppData) => {
        saved = next;
      }),
    };
    let value: ReturnType<typeof useAppStore> | null = null;
    const Probe = () => {
      value = useAppStore();
      return null;
    };
    let renderer: TestRenderer.ReactTestRenderer | undefined;

    await act(async () => {
      renderer = TestRenderer.create(createElement(AppStoreProvider, {store}, createElement(Probe)));
      await Promise.resolve();
      await Promise.resolve();
    });

    const sync = taskReminders.sync as jest.Mock;
    sync.mockClear();
    await act(async () => {
      await value!.setNotificationQuietHours('', '', 60, false);
    });

    expect(saved.tasks[0]?.reminderAtMillis).toBe(task.reminderAtMillis);
    expect((saved.notificationSettings as typeof saved.notificationSettings & {taskRemindersEnabled: boolean}).taskRemindersEnabled).toBe(false);
    expect(sync).toHaveBeenLastCalledWith([]);
    const requestPermission = taskReminders.requestPermission as jest.Mock;
    const schedule = taskReminders.schedule as jest.Mock;
    requestPermission.mockClear();
    schedule.mockClear();
    const replacementReminderAt = Date.now() + 120_000;
    await act(async () => {
      await value!.setTaskReminder('task_pause_category', replacementReminderAt);
    });
    expect(saved.tasks[0]?.reminderAtMillis).toBe(replacementReminderAt);
    expect(requestPermission).not.toHaveBeenCalled();
    expect(schedule).not.toHaveBeenCalled();
    const saveCalls = (store.save as jest.Mock).mock.calls.length;
    await act(async () => {
      await value!.snoozeTaskFromReminder('task_pause_category');
    });
    expect(saved.tasks[0]?.reminderAtMillis).toBe(replacementReminderAt);
    expect((store.save as jest.Mock).mock.calls.length).toBe(saveCalls);
    await act(async () => {
      renderer?.unmount();
    });
  });
});
